<a href="https://colab.research.google.com/github/emdil99/Machine-Learning-Practice/blob/main/MLCC_Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Populating Arrays

In [1]:
import numpy as np

In [2]:
one_dim_array = np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dim_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dim_array = np.array([[6,5],[11,7],[4,8]])
print(two_dim_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
sequence_of_ints = np.arange(5, 12)
print(sequence_of_ints)

[ 5  6  7  8  9 10 11]


In [7]:
test = np.ones((3,5))
print(test)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
random_ints = np.random.randint(low=50, high=101, size=(6,))
print(random_ints)

[72 96 56 92 70 60]


In [12]:
random_floats = np.random.random((6,))
print(random_floats)

[0.99423996 0.99174029 0.86369708 0.29309149 0.79839163 0.03574955]


Mathmatical Operations



In [14]:
random_floats_between_2_and_3 = random_floats + 2.0
print(random_floats_between_2_and_3)

[2.99423996 2.99174029 2.86369708 2.29309149 2.79839163 2.03574955]


In [17]:
random_integers_between_150_and_300 = random_ints * 3
print(random_integers_between_150_and_300)

[216 288 168 276 210 180]


**Independent Tasks **

In [20]:
feature = np.arange(6,21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [22]:
label = (feature *3) +4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [32]:
#add noise by adding a different random floating point between -2 and 2
noise=np.random.random([15])*4-2
print(noise)

[-0.42515703 -1.46636031 -0.45825021 -1.04166324 -1.84555286 -0.68028636
 -1.86899241 -0.69459214  0.37478547 -0.57638171  0.30923235  0.16371014
  0.53111572 -1.66420025 -1.84891071]


In [33]:
label = label + noise
print(label)

[21.68532953 24.44404087 28.05613411 30.3153475  32.46082312 36.5656317
 38.74849736 43.10854589 46.48658842 48.58016759 53.00141622 55.94588997
 59.36165345 59.73552135 62.326238  ]
